print("Ingredients")
print("1 Package of Johnsonville Italian Sausages")
print("2 Cups of Penne Pasta")
print("1 Can of Tomato Sauce")
print("1/2 a medium onion")
print("4 cloves of garlic")
print("Handfull of Parsley")
print("Salt")
print("Pepper")
print("Olive oil")
print("1 tablespoon Red Chili Flakes")

print("Steps")
print("Bring a large pot of water to a boil, add enough salt to make it taste like the ocean. Add the pasta and follow the package instructions")
print("In a sperate pan, fry the sausages in on med-high heat")
print("Dice the onions into medium pieces and garlic to tiny pieces")
print("After a minute of frying the sausages, add the onions into pan and wait until translucent")
print("Add in the red chili flakes and garlic")
print("After the garlic is fragrant, add in tomato sauce.")
print("Add in salt and pepper")
print("Make sure to reserve a quarter cup of the pasta water")
print("Toss in the pasta with the sauce")

